### ISSUE TITLE
AttributeError: 'RawTime' object has no attribute 'get_code'

### ISSUE THREAD

**Issue by XIGRISH** [cnfatal/rpycdec#12]
I looked through a bunch of sites and didn't find anything.

1. OS window 10 2h22
2. Python 3.10
3. Renpy 6.99.12.4

I'm decompiling a large number of .rpyc files, some decompile to .rpy and some don't. And those that are not decompiled give an error:

AttributeError: 'RawTime' object has no attribute 'get_code'

![Снимок экрана (238)](https://github.com/user-attachments/assets/b6f6c0be-7bcb-4a31-b0cf-4570b2b10aeb)

**Comment by cnfatal** [comment]
hi , can you provide the file which can't decompile so that i can fix it.

**Comment by cnfatal** [comment]
Hi  try the latest version `0.1.5` , It may fixed.

**Comment by XIGRISH** [comment]
Thank you very much! It's now working😁
