### ISSUE TITLE
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

### ISSUE THREAD

**Issue by D0n-A** [cnfatal/rpycdec#7]
Good afternoon again!

My configuration is as follows:

1. Windows 11 23H3;
2. Python 3.11.7;
3. RPYC was compiled on RenPy 7.4.11.2266.

When trying to decode the test3.rpyc file, the following error is returned:

```
D:\233>rpycdec D:\233
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\rpycdec.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\rpycdec.py", line 677, in main
    decompile(args.src[0], args.dest)
  File "C:\Python\Lib\site-packages\rpycdec.py", line 578, in decompile
    decompile_file(
  File "C:\Python\Lib\site-packages\rpycdec.py", line 555, in decompile_file
    stmts = load_file(input_file)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rpycdec.py", line 529, in load_file
    bindata = read_rpyc_data(file, slot)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rpycdec.py", line 514, in read_rpyc_data
    return zlib.decompress(data)
           ^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

Decompilation by other utilities (for example, UnRen mastermod by Gideon v.10) is successful, but for some reason there are no comments in the code.

And here's and rpyc itself:
[test3.rpyc.txt](https://github.com/cnfatal/rpycdec/files/15267646/test3.rpyc.txt)

I created the problem separately for easy tracking.
Thank you in advance again!

**Comment by D0n-A** [comment]
It's working, thanks. The only question left is: when decompiling the file, there is a 
`"WARNING:rpycdec.stmts:Failed to read slot 1: Error -5 while decompressing data: incomplete or truncated stream"`

Is this normal, is this how it should be?

**Comment by cnfatal** [comment]
> After the last update - it's working, thanks. The only question left is: when decompiling the file, there is a `"WARNING:rpycdec.stmts:Failed to read slot 1: Error -5 while decompressing data: incomplete or truncated stream"`.
> 
> Is this normal, is this how it should be?

It's a warning, rpycdec try to decode file use slot 1(the most used file format) and slot 2 ,it print the warning if decode slot 1 not work and try slot2.

Just ignore it if there is a decoded file generated. the success log may like:

```log
INFO:rpycdec.decompile:decompile tmp/test_rpycdec.rpyc -> tmp/test_rpycdec.rpy
```
